functional:
  - Пользователь может зарегистрироваться на сайте.
  - Пользователь может войти в систему, используя учетную запись GitHub.
  - Пользователь может запустить игру без входа в систему.
  - Пользователь может восстановить пароль.
  - Пользователь может редактировать профиль.
  - Пользователь может поменять звуки сайта dendy/cs/standart/silent.
  - Пользователь может менять язык программирования.
  - Пользователь может изменять уровень громкости сайта.
  - Total games должен обновляться после каждой игры. 
  - Пользователь может создать игру с другим пользователем или ботом.
  - Пользователю доступен выбор сложности задачки.
  - Пользователю доступен выбор противника.
  - Пользователю доступно выбрать время отводимое на матч. 
  - Сайт должен быть полностью переведен на русский и английский язык.
  - На главной странице должна быть таблица лидеров по очкам с фильтром по времени (за неделю/месяц/все время).
  - На главной странице должно быть лобби с возможностью выбора игрового противника.
  - Пользователь должен получать очки за победу в играх.
  - Пользователь может следить за ходом игры других игроков.
  - На главной странице должно отражаться количество игроков Online.
  - Количество игроков онлайн должно обновлятся при входе/выходе пользователя на сайт.
  - При наведении стрелки мыши на никнейм игрока в таблице лидеров должна появлятся информация о данном пользователе.
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
  - 
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Простота навигации
  - Логичность расположения элементов
  - Современный дизайн
  - Единый стиль
  - Возможность общения
