functional:
  - Пользователь может зарегистрироваться на сайте.
  - Пользователь может войти в систему, используя учетную запись GitHub.
  - Пользователь может войти в систему, используя учетную запись Discord.
  - Пользователь может войти в систему используя логин и пароль.
  - Пользователь может восстановить пароль.
  - Поле для ввода имени в разделе регистрации должно быть от 3 до 16 символов.
  - Поле для ввода имени в разделе регистрации должно быть только на латинице.
  - Поле для ввода пароля в разделе регистрации должно быть от 6 до 16 символов.
  - При авторизации пользователя с уже зарегистрированным email появляется ошибка "Email is already taken".
  - При вводе незарегистрированного email и попытке авторизации появляется ошибка "EMAIL_NOT_FOUND".
  - При входе в профиль и вводе неверного пароля отображается ошибка "INVALID_PASSWORD".
  - При авторизации если оставить поле "email" пустым появляется ошибка "Email required".
  - При авторизации если оставить поле "password" пустым появляется ошибка "Password required". 
  - Пользователь может запустить игру без входа в систему.
  - Пользователь может редактировать профиль.
  - Пользователь может менять настройки профиля.
  - Пользователь может просматривать статистику своего профиля.
  - Пользователь может выйти из профиля.
  - Пользователю доступен рейтинг пользователей.
  - Пользователю доступны задания.
  - Пользователь может создать задание.
  - Название задания должно быть уникальным.
  - При создании задания доступен выбор видимости "hidden/public".
  - Пользователь может просматривать задания. 
  - Пользователь может редактировать задания.
  - Пользователю доступны турниры.
  - Пользователь может просматривать турниры.
  - В списке турниров в графе "state" отображены - "upcoming/active/finished".
  - Имя турнира должно быть уникальным.
  - Пользователь создавший турнир может его удалить.
  - Пользователь создавший турнир может удалять из турнира других пользователей.
  - Пользователь создавший турнир может банить пользователей в чате турнира.
  - Пользователь создавший турнир может очищать список банов в чате турнира.
  - Пользователь создавший закрытый турнир может сделать его открытым.
  - Закрытый турнир могут видеть только пользователи участвующие в нем, а так же пользователь создавший его.
  - Пользователь может выходить из турниров.
  - Турниры с типом доступа "public" доступны для просмотра и участия всем пользователям.
  - Пользователь может создать свой турнир.
  - Пользователь может поменять звуки сайта dendy/cs/standart/silent.
  - Пользователь может менять язык программирования.
  - Пользователь может изменять уровень громкости сайта.
  - Пользователь может создать игру с другим пользователем или ботом.
  - Незарегистрированный пользователь может просматривать историю своей игры с ботом.
  - Незарегистрированный пользователь может пользоваться чатом в игре с ботом.
  - Незарегистрированный пользователь может просматривать "Guide" в игре с ботом.
  - Пользователю доступен выбор сложности задачки.
  - Пользователю доступен выбор противника.
  - Пользователю доступно выбрать время отводимое на матч. 
  - Пользователю доступен выбор категорий заданий.
  - В игровом поле пользователю доступно задание и примеры решения.
  - В игровом поле пользователю доступна смена языка.
  - В игровом поле пользователю доступен гид по интерфейсу игры.
  - В игровом поле пользователю доступен выбор языка программирования.
  - В игровом поле пользователю доступен выбор темы игры "light/dark".
  - Пользователь может сдаться нажав "Give up".
  - Пользователь может обнулить solution. 
  - Пользователь может запустить проверку solution.
  - Пользователю доступен таймер времени игры.
  - Пользователь может просматривать историю своей игры.
  - Пользователю доступен чат с соперником во время игры.
  - Все тексты игрового поля должны отображаться корректно и без орфографических/грамматических ошибок.
  - Корректное отображение и функционал элементов интерфейса.
  - Во время игры в чате с соперником пользователь может выбирать "emoji".
  - Чат должен работать корректно у каждого игрока.
  - Во время игры можно использовать текстовый редактор "Vim".
  - После победы/поражения в игре, возможно сделать "Rematch" игры.
  - При нажатии "Rematch" игры запускает новую игру с настройками предыдущей, с тем же противником.
  - После победы/поражения в игре пользователю показывается победное модальное окно.
  - Победа присуждается первому правильно решившему задачу пользователю.
  - Игра завершается при победе, самостоятельной сдаче, победе противника, сдаче противника, завершении времени.
  - Во время игры пользователю доступно для просмотра игровое поле противника, на нем отображаются все действия пользователя.
  - Пользователь может в процессе игры выходить из игрового поля с последующим возвращением в игру, до ее завершения.
  - Пользователь может отменить игру до ее начала.
  - Сайт должен быть полностью переведен на русский и английский язык.
  - На главной странице должна быть таблица лидеров по очкам с фильтром по времени (за неделю/месяц/все время).
  - На главной странице должно быть лобби с возможностью выбора игрового противника.
  - На главной странице должно быть поле "Tournament".
  - На главной странице должно быть поле "History" для просмотра истории игр.
  - Пользователь должен получать очки за победу в играх.
  - Пользователь может следить за ходом игры других игроков.
  - Пользователь может использовать приватный чат с игроками online
  - Пользователь может отправить приглашение на игру с главной страницы нажав на значек "send fight invite" в виде двух мечей.
  - На главной странице должно отражаться количество игроков online.
  - Количество игроков онлайн должно обновляться при входе/выходе других пользователей на сайт.
  - При наведении стрелки мыши на никнейм игрока в таблице лидеров должна появляться информация о данном пользователе.
  - На главной странице должен быть общий чат со всеми доступными игроками online.
  - В общем чате должна быть возможность отправлять "emoji"
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Простота навигации
  - Логичность расположения элементов
  - Современный дизайн
  - Единый стиль
  - Возможность общения
