functional:
  - Пользователь может зарегистрироваться на сайте.
  - Пользователь может войти в систему, используя учетную запись GitHub.
  - Пользователь может войти в систему, используя учетную запись Discord.
  - Пользователь может войти в систему используя логин и пароль.
  - Пользователь может восстановить пароль.
  - Пользователь может запустить игру без входа в систему.
  - Пользователь может редактировать профиль.
  - Пользователь может менять язык программирования, звуки сайта dendy/cs/standart/silent, громкость в настройках профиля.
  - Пользователь может просматривать статистику своего профиля.
  - Пользователь может выйти из профиля.
  - Пользователю доступен рейтинг всех зарегистрированных пользователей.
  - Пользователь может сортировать рейтинг пользователей по недельному, месячному и общему рейтингу
  - Пользователь может создать игру с другим пользователем или ботом.
  - Незарегистрированный пользователь может просматривать историю своей игры с ботом.
  - Незарегистрированный пользователь может пользоваться чатом в игре с ботом.
  - Зарегистрированный и незарегистрированный пользователь может просматривать "Guide" в игре с ботом.
  - В игровом поле пользователю доступен выбор темы игры "light/dark".
  - Пользователь может сдаться нажав "Give up".
  - Пользователь может обнулить "solution". 
  - Пользователь может запустить проверку "solution".
  - Пользователь может просматривать историю своей игры.
  - Пользователю доступен чат с соперником во время игры.
  - Во время игры в чате с соперником пользователь может выбирать "emoji".
  - После победы/поражения в игре, возможно сделать "Rematch" игры с настройками предыдущей, с тем же противником.
  - Победа присуждается первому правильно решившему задачу пользователю.
  - Игра завершается при победе, самостоятельной сдаче, победе противника, сдаче противника, завершении времени.
  - Во время игры пользователю доступно для просмотра игровое поле противника, на нем отображаются все действия пользователя.
  - Пользователь может отменить игру до ее начала.
  - Пользователь должен получать очки за победу в играх.
  - Пользователь может следить за ходом игры других игроков.
  - Пользователь может использовать приватный чат с игроками online
  - Пользователь может отправить приглашение на игру с главной страницы нажав на значек "send fight invite" в виде двух мечей.
  - На главной странице должно отражаться количество игроков online.
  - Количество игроков онлайн должно обновляться при входе/выходе других пользователей на сайт.
  - При наведении стрелки мыши на никнейм игрока в таблице лидеров должна появляться информация о данном пользователе.
  - На главной странице должен быть общий чат со всеми доступными игроками online.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Простота навигации
  - Логичность расположения элементов
  - Современный дизайн
  - Единый стиль
  - Возможность общения
